/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EgCarbonbadge {
        "theme": string;
        "url": string;
    }
}
declare global {
    interface HTMLEgCarbonbadgeElement extends Components.EgCarbonbadge, HTMLStencilElement {
    }
    var HTMLEgCarbonbadgeElement: {
        prototype: HTMLEgCarbonbadgeElement;
        new (): HTMLEgCarbonbadgeElement;
    };
    interface HTMLElementTagNameMap {
        "eg-carbonbadge": HTMLEgCarbonbadgeElement;
    }
}
declare namespace LocalJSX {
    interface EgCarbonbadge {
        "theme"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "eg-carbonbadge": EgCarbonbadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eg-carbonbadge": LocalJSX.EgCarbonbadge & JSXBase.HTMLAttributes<HTMLEgCarbonbadgeElement>;
        }
    }
}
